update immutable, draft-js, downgrade sass-loader
update immutable to avoid warnings:
```
immutable.js:4655 iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
```
Fixed in: https://github.com/immutable-js/immutable-js/releases/tag/v3.8.0

update draft-js to latest minor version

downgrade sass-loader otherwise i get errors when i try to run the project:
```
   ERROR in ./node_modules/braft-extensions/dist/emoticon.css (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/braft-extensions/dist/emoticon.css)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    TypeError: this.getResolve is not a function
        at Object.loader (C:\Users\bert\Documents\studiohyperdrive\repos\braft-editor\node_modules\sass-loader\dist\index.js:52:26)

```